name: uniroute
description: A Flutter app for role-based login/registration with localization and Firebase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 

  # ðŸ”¥ Firebase Core & Auth
  firebase_core: ^3.15.1
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.11
  firebase_crashlytics: ^4.3.9  # For crash reporting
  firebase_storage: ^12.4.10
  device_info_plus: ^10.0.1  # For device-specific info

  # ðŸ” Social Sign-In
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^7.0.1
  

  # ðŸ—‚ï¸ State Management
  provider: ^6.1.5

  # ðŸ’¾ Local Storage
  shared_preferences: ^2.5.3
  hive: ^2.1.0  # Lightweight local database

  # ðŸ§¾ UI Buttons & Forms
  flutter_signin_button: ^2.0.0
  intl_phone_field: ^3.2.0  # Phone input with formatting
  country_picker: ^2.0.20  # For "Choose Country"
  image_picker: ^0.8.7+3  # Image selection for profile pictures
  cached_network_image: ^3.2.0  # Caching images for better performance
  lucide_icons: ^0.257.0  # Modern icon set
  flutter_secure_storage: ^8.0.0



  # ðŸŒ Localization
  easy_localization: ^3.0.1
  intl: 0.20.2  # Required by easy_localization for formatting
  http: ^1.5.0-beta.2
  email_validator: ^2.0.1  # Email validation
  url_launcher: ^6.3.2 # Open URLs in browser
  logging: ^1.1.0
  js: ^0.6.7
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_map: ^8.2.1 # For custom maps
  latlong2: ^0.9.1
  location: ^5.0.3
  

  # ðŸŽ¨ Animations & Styling
  lottie: ^3.1.0  # Success animation
  animations: ^2.0.11  # For screen transitions
  flutter_spinkit: ^5.2.0  # Loading indicators
  google_fonts: ^6.1.0  # Modern font styles
  fluttertoast: ^8.2.4  # Toast messages


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Recommended lints
  mockito: ^5.4.4  # For unit testing
  build_runner: ^2.4.8  # Needed by mockito

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/map/maps.jpg
    - assets/icons/location_icon.png
    - assets/icons/notification_icon.png
    - assets/icons/user_icon.png

    - assets/images/  # App logo
    - assets/lang/                # Localization files: en.json, tr.json
    - assets/animations/      # Success animation: success.json
    - assets/icons/  # Custom icons
    - assets/map/  # Custom fonts        
